name: Manual Build

on:
  workflow_dispatch:
    inputs:
      build_windows:
        description: 'Build Windows executable'
        required: true
        default: true
        type: boolean
      build_linux:
        description: 'Build Linux executable'
        required: true
        default: true
        type: boolean
      create_artifacts:
        description: 'Upload build artifacts'
        required: true
        default: true
        type: boolean

env:
  PYTHON_VERSION: '3.12'

jobs:
  build-windows:
    runs-on: windows-latest
    if: ${{ inputs.build_windows }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Create virtual environment
      run: |
        python -m venv venv
        
    - name: Install dependencies
      run: |
        .\venv\Scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Windows executable
      run: |
        .\venv\Scripts\activate
        pyinstaller USB-IP-GUI.spec --clean
        
    - name: Create Windows package
      run: |
        mkdir USB-IP-GUI-Windows-Manual
        copy dist\USB-IP-GUI.exe USB-IP-GUI-Windows-Manual\
        copy README.md USB-IP-GUI-Windows-Manual\
        copy LICENSE USB-IP-GUI-Windows-Manual\
        @"
# USB/IP GUI App for Windows (Manual Build)

## Prerequisites
1. Install USB/IP client from: https://github.com/vadimgrn/usbip-win2
2. Or install usbipd-win from: https://github.com/dorssel/usbipd-win

## Usage
1. Extract this package
2. Run USB-IP-GUI.exe
3. The app will guide you through setup
"@ | Out-File -FilePath USB-IP-GUI-Windows-Manual\INSTALL.md -Encoding UTF8
        powershell Compress-Archive -Path USB-IP-GUI-Windows-Manual\* -DestinationPath USB-IP-GUI-Windows-Manual.zip
        
    - name: Upload Windows artifact
      if: ${{ inputs.create_artifacts }}
      uses: actions/upload-artifact@v4
      with:
        name: USB-IP-GUI-Windows-Manual
        path: USB-IP-GUI-Windows-Manual.zip
        retention-days: 7
        
  build-linux:
    runs-on: ubuntu-latest
    if: ${{ inputs.build_linux }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-venv
        
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        
    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Linux executable
      run: |
        source venv/bin/activate
        pyinstaller USB-IP-GUI-linux.spec --clean
        
    - name: Create Linux package
      run: |
        chmod +x prepare-release-linux.sh
        ./prepare-release-linux.sh
        # Rename to avoid conflicts
        mv USB-IP-GUI-Linux.tar.gz USB-IP-GUI-Linux-Manual.tar.gz
        
    - name: Upload Linux artifact
      if: ${{ inputs.create_artifacts }}
      uses: actions/upload-artifact@v4
      with:
        name: USB-IP-GUI-Linux-Manual
        path: USB-IP-GUI-Linux-Manual.tar.gz
        retention-days: 7
